# Generated by Django 2.2.2 on 2019-06-08 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 22, 34, 3, 653752)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ref',
            field=models.CharField(default='VpJz67khsxdyA85mz4qvmQdLd5zJTHF4', max_length=255),
        ),
    ]
